---
title: "Week#5"
author: "Ravinder Singh"
date: "2023-02-09"
output: html_document
---


```{r}
ps_matchR <- function(x) {
  
  match_expected <- as.matrix(dist(x))
  diag(match_expected) <- .Machine$integer.max
  indices <- apply(match_expected, 1, which.min)
  
  list(
    match_id = as.integer(unname(indices)),
    match_x  = x[indices]
  )
}
```

```{Rcpp}
#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::export]]
List ps_match1(const NumericVector & x) {
  
  int n = x.size();
  IntegerVector indicies(n);
  NumericVector values(n);
  
  for (int i = 0; i < n; ++i) {
    int best_neigh = 0;
    double best_dist = std::numeric_limits< double >::max();
    for (int j = 0; j < n; ++j){
      
      if (i==j)
        continue;
      
      double tmp_dist = abs(x[i]-x[j]);
      if (tmp_dist < best_dist){
        best_dist = tmp_dist;
        best_neigh = j;
      }
    }
    indicies[i]=best_neigh;
    values[i] = x[best_neigh];
    
  }
  
  return List::create(_["match_id"]=indicies, _["match_x"]=values);
  
}
```


```{r}
# Compare

set.seed(100)
x <- runif(10)

ps_match1(x)
ps_matchR(x)
```

```{Rcpp}
// Better version

#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::export]]
List ps_match1(const NumericVector & x) {
  
  int n = x.size();
  IntegerVector indicies(n);
  NumericVector values(n);
  
  for (int i = 0; i < n; ++i) {
    int best_neigh = 0;
    double best_dist = std::numeric_limits< double >::max();
    for (int j = 0; j < n; ++j){
      
      if (i==j)
        continue;
      
      double tmp_dist = abs(x[i]-x[j]);
      if (tmp_dist < best_dist){
        best_dist = tmp_dist;
        best_neigh = j;
      }
    }
    indicies[i]=best_neigh;
    values[i] = x[best_neigh];
    
  }
  
  return List::create(_["match_id"]=indicies, _["match_x"]=values);
  
}
```


```{Rcpp}
// Even better version

#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::export]]
List ps_match3(const NumericVector & x) {
  
  int n = static_cast<int>(x.size());
  
  IntegerVector indices(n);
  NumericVector values(n);
  values.fill(std::numeric_limits< double >::max());
  
  for (int i = 0; i < n; ++i) {
    
    // Instead of allocating new memory, we can point by reference
    // (saves operations)
    double & cur_best = values[i]; 
    auto & cur_i    = indices[i];
    
    for (int j = 0; j < i; ++j) {
      
      // If it is lower, then update
      double d = std::abs(x[i] - x[j]);
      if (d < cur_best) {
        
        cur_best = d;
        cur_i    = j;
        
      }
      
      if (d < values[j]) {
        
        values[j] = d;
        indices[j] = i;
        
      }
      
    }
    
  }
  
  for (int i = 0; i < n; ++i) 
    values[i] = x[indices[i]];
  
  return List::create(
    _["match_id"] = indices + 1, // We add one to match R's indices
    _["match_x"]  = values 
  );
  
}
```



